version: "3"
services:
  vault:
    container_name: vault
    image: vault:latest
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    networks:
      konfig-test:
        aliases:
          - vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: swordfish
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: swordfish
  consul:
    container_name: consul
    image: consul:latest
    ports:
      - "8500:8500"
    volumes:
      - ./consul_config/:/consul/config/
    networks:
      konfig-test:
        aliases:
          - consul
    environment:
      CONSUL_UI_BETA: "true"
networks:
  konfig-test:
